package com.example.SenaiS10;

public enum Especialidade {
    ANESTESIOLOGIA,
    CARDIOLOGIA,
    DERMATOLOGIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    GINECOLOGIA,
    HEMATOLOGIA,
    NEFROLOGIA,
    NEUROLOGIA,
    OFTALMOLOGIA,
    ONCOLOGIA,
    ORTOPEDIA,
    OTORRINOLARINGOLOGIA,
    PEDIATRIA,
    PSIQUIATRIA,
    RADIOLOGIA,
    REUMATOLOGIA,
    UROLOGIA
}

